apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-certificate
spec:
  dnsNames:
    - janus-idp.apps.smaug.na.operate-first.cloud
    - showcase.janus-idp.io
  issuerRef:
    name: letsencrypt
  secretName: janus-idp-cert
