apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: backstage-showcase-bucket-claim
spec:
  generateBucketName: backstage-showcase-bucket-claim-
  storageClassName: openshift-storage.noobaa.io
