apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: janus-idp
resources: 
  - certificate.yaml
  - deploymentconfig.yaml
  - ingress.yaml
  - service.yaml
labels:
  - pairs:
      application: keycloak
    includeSelectors: false
